### ISSUE TITLE
Past Events Archive

### ISSUE THREAD

**Issue by IshaanAdarsh** [NITRR-Open-Source-Community/NOSC-Website#29]
**Description:** Let's create an archive section on the events page for past events. This will allow visitors to access details and resources from previous events.

- **Task:** Design an archive section with links to past event detail pages.
- **Additional Info:** Ensure that past events are categorized by date or topic for easy navigation.
- **Labels:** Enhancement, Events

**Comment by mhsh312** [comment]
I would like to contribute to this feature. Please assign it me.

**Comment by IshaanAdarsh** [comment]
> I would like to contribute to this feature. Please assign it me.

Hello @mhsh312 I have already assigned you another issue. Please complete that, so I can assign you some more

**Comment by DaSeeker67** [comment]
I would like to contribute to this feature, I want to know like do you need some button to open the archive or it should be just a normal section in the achievements page,  and i want to know the past event detail page link

**Comment by DaSeeker67** [comment]
Is it correct this is a past event dive with a filter functionality with hackathons coding fest and speaker session as filters the list is populated using js, and since past events links is not given so i had to give randome url ![image](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/65525769/5d282cb2-c9f1-4004-9881-2efd175c98b8)

![image](https://github.com/NITRR-Open-Source-Community/NOSC-Website/assets/65525769/fb8776e0-0e06-4c4a-9354-eca906513e62)

**Comment by nown1ne** [comment]
as we are just starting out we dont have links for the past events 
your implementation looks pretty good proceed with this
